//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatagridView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thong_tinSV
    {
        public int STT { get; set; }
        public string hoten { get; set; }
        public string quequan { get; set; }
        public string dienthoai { get; set; }
    }
}
